const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"地区类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryDiqu"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"地区管理",
                        "menuJump":"列表",
                        "tableName":"diqu"
                    }
                ],
                "menu":"地区管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "导入导出",
                            "报表",
                            "修改",
                            "删除"
                        ],
                        "menu":"老师管理",
                        "menuJump":"列表",
                        "tableName":"laoshi"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"居家管理",
                        "menuJump":"列表",
                        "tableName":"laoshijujia"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "报表",
                            "删除"
                        ],
                        "menu":"打卡管理",
                        "menuJump":"列表",
                        "tableName":"laoshidaka"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "审核",
                            "修改",
                            "删除"
                        ],
                        "menu":"老师返校申请管理",
                        "menuJump":"列表",
                        "tableName":"laoshifanxiaoshenqing"
                    }
                ],
                "menu":"老师管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"疫情资讯管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"疫情资讯管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表",
                            "导入导出",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "审核",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生返校申请管理",
                        "menuJump":"列表",
                        "tableName":"fanxiaoshenqing"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"居家管理",
                        "menuJump":"列表",
                        "tableName":"xueshengjujia"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "审核",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生请假申请管理",
                        "menuJump":"列表",
                        "tableName":"qingjiashenqing"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "报表",
                            "修改",
                            "删除"
                        ],
                        "menu":"打卡管理",
                        "menuJump":"列表",
                        "tableName":"xueshengdaka"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生留言管理",
                        "menuJump":"列表",
                        "tableName":"xueshengliuyan"
                    }
                ],
                "menu":"学生留言管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"地区管理",
                        "menuJump":"列表",
                        "tableName":"diqu"
                    }
                ],
                "menu":"地区管理"
            }
            ,{
                "child":[
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"居家管理",
                        "menuJump":"列表",
                        "tableName":"laoshijujia"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"打卡管理",
                        "menuJump":"列表",
                        "tableName":"laoshidaka"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"老师返校申请管理",
                        "menuJump":"列表",
                        "tableName":"laoshifanxiaoshenqing"
                    }
                ],
                "menu":"老师管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"疫情资讯管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"疫情资讯管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"学生返校申请管理",
                        "menuJump":"列表",
                        "tableName":"fanxiaoshenqing"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"居家管理",
                        "menuJump":"列表",
                        "tableName":"xueshengjujia"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"学生请假申请管理",
                        "menuJump":"列表",
                        "tableName":"qingjiashenqing"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"打卡管理",
                        "menuJump":"列表",
                        "tableName":"xueshengdaka"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"学生留言管理",
                        "menuJump":"列表",
                        "tableName":"xueshengliuyan"
                    }
                ],
                "menu":"学生留言管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"老师",
        "tableName":"laoshi"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"地区管理",
                        "menuJump":"列表",
                        "tableName":"diqu"
                    }
                ],
                "menu":"地区管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"疫情资讯管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"疫情资讯管理"
            }
            ,{
                "child":[
                    
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"学生返校申请管理",
                        "menuJump":"列表",
                        "tableName":"fanxiaoshenqing"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"居家管理",
                        "menuJump":"列表",
                        "tableName":"xueshengjujia"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"学生请假申请管理",
                        "menuJump":"列表",
                        "tableName":"qingjiashenqing"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"打卡管理",
                        "menuJump":"列表",
                        "tableName":"xueshengdaka"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"学生留言管理",
                        "menuJump":"列表",
                        "tableName":"xueshengliuyan"
                    }
                ],
                "menu":"学生留言管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"学生",
        "tableName":"xuesheng"
    }
]
    }
}
export default menu;
